package model;
// Generated 08/04/2015 07:36:29 by Hibernate Tools 3.6.0


import dao.AcompanhamentoMensalDAO;
import java.sql.SQLException;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Acompanhamentomensal generated by hbm2java
 */
@Entity
@Table(name="acompanhamentomensal"
    ,catalog="scp"
)
public class Acompanhamentomensal  implements java.io.Serializable {


     private int numeroRegistroAcompanhamentoMensal;
     private Projeto projeto;
     private Aluno aluno;
     private String situacao;
     private String avaliacaoProfessor;
     private String comentario;

    public Acompanhamentomensal() {
    }

    public Acompanhamentomensal(int numeroRegistroAcompanhamentoMensal, String situacao, String avaliacaoProfessor, String comentario, Aluno aluno, Projeto projeto) {
        this.numeroRegistroAcompanhamentoMensal = numeroRegistroAcompanhamentoMensal;
        this.situacao = situacao;
        this.avaliacaoProfessor = avaliacaoProfessor;
        this.comentario = comentario;
        this.aluno = aluno;
        this.projeto = projeto;
    }

    
    
     @Id 

    
    @Column(name="numeroRegistroAcompanhamentoMensal", unique=true, nullable=false)
    public int getNumeroRegistroAcompanhamentoMensal() {
        return this.numeroRegistroAcompanhamentoMensal;
    }
    
    public void setNumeroRegistroAcompanhamentoMensal(int numeroRegistroAcompanhamentoMensal) {
        this.numeroRegistroAcompanhamentoMensal = numeroRegistroAcompanhamentoMensal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="numeroRegistroProjeto", nullable=false)
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="numeroRegistroAluno", nullable=false)
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    
    @Column(name="situacao", length=500)
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    
    @Column(name="avaliacaoProfessor", length=500)
    public String getAvaliacaoProfessor() {
        return this.avaliacaoProfessor;
    }
    
    public void setAvaliacaoProfessor(String avaliacaoProfessor) {
        this.avaliacaoProfessor = avaliacaoProfessor;
    }

    
    @Column(name="comentario", length=500)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    public static List<Acompanhamentomensal> obterAcompanhamentosMensais () throws ClassNotFoundException, SQLException {
            return AcompanhamentoMensalDAO.obterAcompanhamentosMensais();
    }
    
    

    public static Acompanhamentomensal obterAcompanhamentoMensal (int id) throws ClassNotFoundException, SQLException{
        return AcompanhamentoMensalDAO.obterAcompanhamentoMensal(id);
        
    }

    public void gravar() throws SQLException, ClassNotFoundException{
        AcompanhamentoMensalDAO.gravar(this);
    }
    
    public void alterar() throws SQLException, ClassNotFoundException{
        AcompanhamentoMensalDAO.alterar(this);
    }
    public void excluir() throws SQLException, ClassNotFoundException{
        AcompanhamentoMensalDAO.excluir(this);
    }




}


