package model;
// Generated 08/04/2015 07:36:29 by Hibernate Tools 3.6.0

import dao.AreaConhecimentoDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Areaconhecimento generated by hbm2java
 */
@Entity
@Table(name = "areaconhecimento", catalog = "scp"
)
public class Areaconhecimento implements java.io.Serializable {

    private int numeroRegistroAreaConhecimento;
    private String nome;

    public Areaconhecimento(int numeroRegistroAreaConhecimento, String nome) {
        this.numeroRegistroAreaConhecimento = numeroRegistroAreaConhecimento;
        this.nome = nome;
    }
   
    public Areaconhecimento() {
    }

   

    @Id

    @Column(name = "numeroRegistroAreaConhecimento", unique = true, nullable = false)
    public int getNumeroRegistroAreaConhecimento() {
        return this.numeroRegistroAreaConhecimento;
    }

    public void setNumeroRegistroAreaConhecimento(int numeroRegistroAreaConhecimento) {
        this.numeroRegistroAreaConhecimento = numeroRegistroAreaConhecimento;
    }

    @Column(name = "nome", length = 45)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

   
    public static List<Areaconhecimento> obterAreasconhecimento() throws ClassNotFoundException, SQLException {
        return AreaConhecimentoDAO.obterAreasConhecimento();
    }

    public static Areaconhecimento obterAreaConhecimento(int id) throws ClassNotFoundException, SQLException {
        return AreaConhecimentoDAO.obterAreaConhecimento(id);

    }

    public void gravar() throws SQLException, ClassNotFoundException {
        AreaConhecimentoDAO.gravar(this);
    }

    public void alterar() throws SQLException, ClassNotFoundException {
        AreaConhecimentoDAO.alterar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        AreaConhecimentoDAO.excluir(this);
    }

}
