package model;
// Generated 08/04/2015 07:36:29 by Hibernate Tools 3.6.0


import dao.CursoDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="scp"
)
public class Curso  implements java.io.Serializable {


     private int numeroRegistroCurso;
     private Nucleo nucleo;
     private String nomeCurso;

    public Curso(int numeroRegistroCurso, String nomeCurso, Nucleo nucleo) {
        this.numeroRegistroCurso = numeroRegistroCurso;
        this.nucleo = nucleo;
        this.nomeCurso = nomeCurso;
    }
    
    public Curso() {
    }

	
    
   
     @Id 

    
    @Column(name="numeroRegistroCurso", unique=true, nullable=false)
    public int getNumeroRegistroCurso() {
        return this.numeroRegistroCurso;
    }
    
    public void setNumeroRegistroCurso(int numeroRegistroCurso) {
        this.numeroRegistroCurso = numeroRegistroCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="numeroRegistroNucleo", nullable=false)
    public Nucleo getNucleo() {
        return this.nucleo;
    }
    
    public void setNucleo(Nucleo nucleo) {
        this.nucleo = nucleo;
    }

    
    @Column(name="nomeCurso", length=45)
    public String getNomeCurso() {
        return this.nomeCurso;
    }
    
    public void setNomeCurso(String nomeCurso) {
        this.nomeCurso = nomeCurso;
    }
    
    public static List<Curso> obterCursos () throws ClassNotFoundException, SQLException {
            return CursoDAO.obterCursos();
    }
    
     

    public static Curso obterCurso (int id) throws ClassNotFoundException, SQLException{
        return CursoDAO.obterCurso(id);
        
    }

    public void gravar() throws SQLException, ClassNotFoundException{
        CursoDAO.gravar(this);
    }
    
    public void alterar() throws SQLException, ClassNotFoundException{
        CursoDAO.alterar(this);
    }
    public void excluir() throws SQLException, ClassNotFoundException{
        CursoDAO.excluir(this);
    }





}


