package model;
// Generated 08/04/2015 07:36:29 by Hibernate Tools 3.6.0


import dao.ProjetoDAO;
import java.sql.SQLException;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Projeto generated by hbm2java
 */
@Entity
@Table(name="projeto"
    ,catalog="scp"
)
public class Projeto  implements java.io.Serializable {


     private int numeroRegistroProjeto;
     private Areaconhecimento areaconhecimento;
     private Edital edital;
     private Professor professor;
     private String nomeProjeto;
     private String implementacao;
     private String dataInicio;
     private String dataTermino;
     private String renovacao;
     private String cargaHorariaSemanal;
     private String justificativaProblema;
     private String referencialTeorico;
     private String objetivo;
     private String metodologia;
     private String resultadoEsperado;
     private String cronograma;
     private String orcamento;
     private String referenciaBibliografica;

    public Projeto() {
    }

    public Projeto(int numeroRegistroProjeto, Areaconhecimento areaconhecimento, Edital edital, Professor professor, String nomeProjeto, String implementacao, String dataInicio, String dataTermino, String renovacao, String cargaHorariaSemanal, String justificativaProblema, String referencialTeorico, String objetivo, String metodologia, String resultadoEsperado, String cronograma, String orcamento, String referenciaBibliografica) {
        this.numeroRegistroProjeto = numeroRegistroProjeto;
        this.areaconhecimento = areaconhecimento;
        this.edital = edital;
        this.professor = professor;
        this.nomeProjeto = nomeProjeto;
        this.implementacao = implementacao;
        this.dataInicio = dataInicio;
        this.dataTermino = dataTermino;
        this.renovacao = renovacao;
        this.cargaHorariaSemanal = cargaHorariaSemanal;
        this.justificativaProblema = justificativaProblema;
        this.referencialTeorico = referencialTeorico;
        this.objetivo = objetivo;
        this.metodologia = metodologia;
        this.resultadoEsperado = resultadoEsperado;
        this.cronograma = cronograma;
        this.orcamento = orcamento;
        this.referenciaBibliografica = referenciaBibliografica;
    }
     
    
   
     @Id 

    
    @Column(name="numeroRegistroProjeto", unique=true, nullable=false)
    public int getNumeroRegistroProjeto() {
        return this.numeroRegistroProjeto;
    }
    
    public void setNumeroRegistroProjeto(int numeroRegistroProjeto) {
        this.numeroRegistroProjeto = numeroRegistroProjeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="numeroRegistroAreaConhecimento", nullable=false)
    public Areaconhecimento getAreaconhecimento() {
        return this.areaconhecimento;
    }
    
    public void setAreaconhecimento(Areaconhecimento areaconhecimento) {
        this.areaconhecimento = areaconhecimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="numeroRegistroEdital", nullable=false)
    public Edital getEdital() {
        return this.edital;
    }
    
    public void setEdital(Edital edital) {
        this.edital = edital;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="numeroRegistroOrientador", nullable=false)
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }

    
    @Column(name="nomeProjeto", length=45)
    public String getNomeProjeto() {
        return this.nomeProjeto;
    }
    
    public void setNomeProjeto(String nomeProjeto) {
        this.nomeProjeto = nomeProjeto;
    }

    
    @Column(name="implementacao", length=1)
    public String getImplementacao() {
        return this.implementacao;
    }
    
    public void setImplementacao(String implementacao) {
        this.implementacao = implementacao;
    }

    
    @Column(name="dataInicio", length=10)
    public String getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(String dataInicio) {
        this.dataInicio = dataInicio;
    }

    
    @Column(name="dataTermino", length=10)
    public String getDataTermino() {
        return this.dataTermino;
    }
    
    public void setDataTermino(String dataTermino) {
        this.dataTermino = dataTermino;
    }

    
    @Column(name="renovacao", length=45)
    public String getRenovacao() {
        return this.renovacao;
    }
    
    public void setRenovacao(String renovacao) {
        this.renovacao = renovacao;
    }

    
    @Column(name="cargaHorariaSemanal", length=45)
    public String getCargaHorariaSemanal() {
        return this.cargaHorariaSemanal;
    }
    
    public void setCargaHorariaSemanal(String cargaHorariaSemanal) {
        this.cargaHorariaSemanal = cargaHorariaSemanal;
    }

    
    @Column(name="justificativaProblema", length=500)
    public String getJustificativaProblema() {
        return this.justificativaProblema;
    }
    
    public void setJustificativaProblema(String justificativaProblema) {
        this.justificativaProblema = justificativaProblema;
    }

    
    @Column(name="referencialTeorico", length=500)
    public String getReferencialTeorico() {
        return this.referencialTeorico;
    }
    
    public void setReferencialTeorico(String referencialTeorico) {
        this.referencialTeorico = referencialTeorico;
    }

    
    @Column(name="objetivo", length=500)
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }

    
    @Column(name="metodologia", length=500)
    public String getMetodologia() {
        return this.metodologia;
    }
    
    public void setMetodologia(String metodologia) {
        this.metodologia = metodologia;
    }

    
    @Column(name="resultadoEsperado", length=500)
    public String getResultadoEsperado() {
        return this.resultadoEsperado;
    }
    
    public void setResultadoEsperado(String resultadoEsperado) {
        this.resultadoEsperado = resultadoEsperado;
    }

    
    @Column(name="cronograma", length=500)
    public String getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(String cronograma) {
        this.cronograma = cronograma;
    }

    
    @Column(name="orcamento", length=500)
    public String getOrcamento() {
        return this.orcamento;
    }
    
    public void setOrcamento(String orcamento) {
        this.orcamento = orcamento;
    }

    
    @Column(name="referenciaBibliografica", length=500)
    public String getReferenciaBibliografica() {
        return this.referenciaBibliografica;
    }
    
    public void setReferenciaBibliografica(String referenciaBibliografica) {
        this.referenciaBibliografica = referenciaBibliografica;
    }

    public static List<Projeto> obterProjetos () throws ClassNotFoundException, SQLException {
            return ProjetoDAO.obterProjetos();
    }
    
     

    public static Projeto obterProjeto (int id) throws ClassNotFoundException, SQLException{
        return ProjetoDAO.obterProjeto(id);
        
    }

    public void gravar() throws SQLException, ClassNotFoundException{
        ProjetoDAO.gravar(this);
    }
    
    public void alterar() throws SQLException, ClassNotFoundException{
        ProjetoDAO.alterar(this);
    }
    public void excluir() throws SQLException, ClassNotFoundException{
        ProjetoDAO.excluir(this);
    }


}


